import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import useSpotify from "../hooks/useSpotify";

function artists() {
  const spotifyApi = useSpotify();
  const [topTracks, setTopTracks] = useState([]);
  const [timePeriod, setTimePeriod] = useState("short_term");
  const [loading, setLoading] = useState(false);

  const { data: session } = useSession();
  return (
    <div className="flex h-screen bg-gray-800 ">
      <Head>
        <title>Top Artists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className=" w-screen bg-gray-800  overflow-y-scroll   ">
        <Header />

        <h3 className="text-3xl text-white text-center uppercase tracking-wide">
          Most Played Artists
        </h3>
      </div>
    </div>
  );
}

export default artists;

//(when refreshing the page -> data is not shown. solution) ->
//onload issue -> pre-fetch the session / pre render the user -> data is shown.
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
