import { ArrowRightCircleIcon } from "@heroicons/react/24/solid";
import { RaceBy, Waveform } from "@uiball/loaders";
import { getSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useRef, useState } from "react";

import Artist from "../components/Artist";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import Song from "../components/Song";
import useSpotify from "../hooks/useSpotify";

import styles from "../styles/effects.module.css";

export default function discover() {
  const spotifyApi = useSpotify();

  const [topArtists, setTopArtists] = useState([]);
  const [loadingArtists, setLoadingArtists] = useState(true);
  const [artistsSelected, setArtistsSelected] = useState([]);

  const getArtists = () => {
    spotifyApi
      .getMyTopArtists({ limit: 14, time_range: "long_term" })
      .then((data) => setTopArtists(data.body.items))
      .then(() => setLoadingArtists(false))
      .catch((err) => console.log(err));
  };
  useEffect(() => {
    if (spotifyApi.getAccessToken()) {
      setLoadingArtists(true);
      //increase loading-spinner time -> more ux friendly
      setTimeout(() => {
        getArtists();
      }, 500);
    }
  }, []);

  /* input range */
  const [popularity, setPopularity] = useState(0);
  const handlePopularityChange = (event) => {
    const newPopularity = Math.round(event.target.value / 10) * 10;
    setPopularity(newPopularity);
  };
  const [energy, setEnergy] = useState(0);
  const handleEnergyChange = (event) => {
    const newEnergy = Math.round(event.target.value / 10) * 10;
    setEnergy(newEnergy);
  };

  const [recommendations, setRecommendations] = useState([]);
  const [loadingRecommendations, setLoadingRecommendations] = useState(false);
  // increase loading time..?
  const handleGetRecommendations = () => {
    setLoadingRecommendations(true);
    spotifyApi
      .getRecommendations({
        min_energy: 0.4,
        seed_artists: ["0cAOG10Gh3ORpBRZ9c7Zam"],
        min_popularity: 50,
        limit: 10,
        //min_danceability
      })
      .then((data) => setRecommendations(data.body.tracks))
      .then(() => setLoadingRecommendations(false))
      .catch((err) => console.log(err));
  };

  const containerRef = useRef(null);

  const handleArrowClick = (scrollOffset) => {
    containerRef.current.scrollTo({
      left: containerRef.current.scrollLeft + scrollOffset,
      behavior: "smooth",
    });
  };

  return (
    <div className="flex h-screen ">
      <Head>
        <title> Spotify Stats: Discover </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />

      <div className=" w-screen   overflow-y-scroll  bg-bodyBackground">
        <Header />

        {loadingArtists ? (
          <div className="flex justify-center  mt-28">
            <RaceBy color="white" speed={1.2} size={150} lineWeight={4} />
          </div>
        ) : (
          <>
            <h1
              aria-label="ignore-pause"
              //onClick={() => console.log(recommendations)}
              className="text-3xl mt-1.5 text-white text-center uppercase tracking-wide"
            >
              Discover
            </h1>
            <h3 className="text-white text-center mt-0.5 mb-1 text-base ">
              Select up to 3 artists and adjust popularity & energy
            </h3>

            <div className="relative bg-red-400  flex justify-end items-center ">
              <div
                ref={containerRef}
                className={`     ${styles.hideScrollbar} justify-start/  overflow-x-scroll    flex mx-5 mdlg:grid mdlg:grid-cols-7 mdlg:gap-1 mdlg:space-x-0 space-x-2       `}
              >
                {topArtists.map((artist, i) => (
                  <Artist
                    key={i}
                    artist={artist}
                    discoverPage
                    artistsSelected={artistsSelected}
                    setArtistsSelected={setArtistsSelected}
                  />
                ))}
              </div>

              <ArrowRightCircleIcon
                onClick={() => handleArrowClick(250)}
                className="text-white  absolute  h-8 w-8 z-50 mb-4 mr-1 cursor-pointer "
              />
            </div>
            <div
              aria-label="INPUT RANGE DIV"
              className="mx-5 flex space-x-5 justify-between mt-3"
            >
              <div className="text-center  w-full">
                <input
                  type="range"
                  min="0"
                  max="100"
                  value={popularity}
                  onChange={handlePopularityChange}
                  className={`${styles.rangeInput} bg-gray-700 `}
                />
                <p className="mt-2 text-lg text-gray-700 ">
                  Min Popularity: {popularity}
                </p>
              </div>

              <div className="text-center w-full">
                <input
                  type="range"
                  min="0"
                  max="100"
                  step="10"
                  value={energy}
                  onChange={handleEnergyChange}
                  className={`${styles.rangeInput} bg-gray-700          /w-full /h-1 /bg-gray-700 /outline-none /appearance-none /rounded `}
                />
                <p className="mt-2 text-lg text-gray-700">
                  Min Energy: {energy}
                </p>
              </div>
            </div>

            <div className="flex justify-center mt-2">
              <button
                disabled={artistsSelected.length == 0}
                onClick={() => handleGetRecommendations()}
                className=" text-white border border-white rounded-xl px-3 py-2  "
              >
                Get Recommendations
              </button>
            </div>

            {loadingRecommendations ? (
              <div className="flex justify-center mt-4">
                <Waveform color="white" speed={0.8} />
              </div>
            ) : (
              <div className="!mx-4 gap-3 my-3 grid grid-cols-1 xs:grid-cols-2  md:grid-cols-3 mdlg:grid-cols-4 lg:grid-cols-5 lg:mx-auto lg:px-2 max-w-4xl ">
                {recommendations
                  //error issue: some tracks dont have preview_url -> solution, filter out->
                  ?.filter((track) => track.preview_url !== null)
                  .map((_track, i) => (
                    <Song key={i} track={_track} />
                  ))}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

//(when refreshing the page -> data is not shown. solution) ->
//onload issue -> pre-fetch the session / pre render the user -> data is shown.
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
