import { getSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import Body from "../components/Body";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className="flex h-screen ">
      <Head>
        <title>Pete Spotify Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* SIDEBAR */}
      <Sidebar />

      {/* BODY */}
      <Body />
    </div>
  );
}

//onload issue -> pre-fetch the session / pre render the user ->
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
