import Head from "next/head";
import React from "react";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";

function info() {
  return (
    <div className="flex h-screen ">
      <Head>
        <title> Spotify Stats: info </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />

      <div className=" w-screen   overflow-y-scroll  bg-bodyBackground">
        <Header />

        <h1 className="text-3xl text-white text-center uppercase tracking-wide">
          Info
        </h1>

        <p className="text-center text-white mx-2 max-w-[640px] sm:mx-auto">
          This is not an officially Spotify supported web-app. No copyright
          infringement is intended. The project is made for learning purposes
          using the official Spotify API.
        </p>
      </div>
    </div>
  );
}

export default info;
